### ISSUE TITLE
About deprecated streamer

### ISSUE THREAD

**Issue by zckrs** [mroth/emojitracker#35]
Hi,
Do you deprecate Ruby and NodeJS versions because issue performance ? 

Your feedback on why depreciation should be very interesting.

**Comment by mroth** [comment]
Hi there, you can find a detailed writeup of the transition in this blog post:
https://medium.com/@mroth/how-i-kept-building-emojitracker-c31378810136#.7ovr5mt98 in the section "Optimizing High Volume Streams".
